development:
  adapter: postgresql
  host: localhost
  database: benchup_dev2
  username: postgres
  password: password
test:
  adapter: postgresql
  host: localhost
  database: benchup_test2
  username: postgres
  password: password